#!/bin/sh

# remove DRI modules in case of fglrx/nvidia blobs
stat /lib/modules/*/fglrx >&/dev/null \
&& rm -rf /lib/modules/*/kernel/drivers/gpu/drm/radeon/ \
&& rpm -e xorg-drv-ati xorg-drv-radeon xorg-dri-radeon

stat /lib/modules/*/nVidia >&/dev/null \
&& rm -rf /lib/modules/*/kernel/drivers/gpu/drm/nouveau/ \
&& rpm -e xorg-drv-nouveau xorg-drv-nv xorg-dri-nouveau

:
