#!/bin/sh -e
# initiate CPU microcode update on boot

cat << EOF > /usr/local/sbin/microcode_update
#!/bin/sh -e
echo 1 > /sys/devices/system/cpu/microcode/reload
EOF
chmod +x /usr/local/sbin/microcode_update

cat << EOF > /etc/systemd/system/microcode.service
[Unit]
Description=Reload CPU microcode

[Service]
ExecStart=/usr/local/sbin/microcode_update
Type=oneshot
RemainAfterExit=yes

[Install]
WantedBy=default.target
EOF

systemctl enable microcode.service
