#!/bin/sh

cd /etc/X11 || exit 1

if [ -f /lib/modules/*/nVidia/nvidia.ko ]; then
cat > xorg.conf << EOF
Section "Device"
	Identifier	"Nvidia GPU"
	Driver		"nvidia"
	# EDID could report this incorrectly so disable
	Option "UseEdidDpi" "false"
EndSection
EOF
fi
:
