#!/bin/sh

# remove DRI modules in case of fglrx/nvidia blobs
stat /lib/modules/*/fglrx >&/dev/null \
&& rm -rf /lib/modules/*/kernel/drivers/gpu/drm/radeon/

stat /lib/modules/*/nVidia >&/dev/null \
&& rm -rf /lib/modules/*/kernel/drivers/gpu/drm/nouveau/

:
